#!/usr/bin/env python3
"""
PR Agent Runner - Real implementation that generates detection modules and submits PRs.

This script is called to process discoveries and generate new scanner modules.
"""

import sys
import os
import json
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.manager import agent_manager

PROJECT_DIR = Path(__file__).parent.parent
MODULES_DIR = PROJECT_DIR / "modules"
REPO = "XY-world/fqdn-security-scanner"


def generate_module_code(name: str, description: str, check_type: str) -> str:
    """Generate a new scanner module based on discovery."""
    
    class_name = "".join(word.title() for word in name.split("_")) + "Scanner"
    
    code = f'''#!/usr/bin/env python3
"""
{name} Scanner - {description}

Auto-generated by PR Agent based on security discovery.
Category: {check_type}
Generated: {datetime.now(timezone.utc).isoformat()}
"""

from typing import Dict, List
from .base import BaseScanner, Finding, Severity


class {class_name}(BaseScanner):
    """Scanner for {description}."""
    
    name = "{name}"
    description = "{description}"
    
    def scan(self, target: str, timeout: int = 30) -> Dict:
        """
        Run the security check.
        
        Args:
            target: Domain to scan
            timeout: Timeout in seconds
            
        Returns:
            Dict with status and findings
        """
        findings: List[Finding] = []
        
        try:
            # TODO: Implement specific detection logic for {check_type}
            # This is a placeholder - implement real detection here
            
            # Example finding structure:
            # findings.append(Finding(
            #     title="Issue Found",
            #     description="Description of the issue",
            #     severity=Severity.MEDIUM,
            #     remediation="How to fix this issue"
            # ))
            
            pass
            
        except Exception as e:
            return {{
                "status": "error",
                "error": str(e),
                "findings": []
            }}
        
        return {{
            "status": "completed",
            "findings": [f.to_dict() for f in findings],
        }}


# Register scanner
def register():
    """Register this scanner module."""
    return {class_name}
'''
    return code


def create_branch_and_pr(module_name: str, module_code: str, discovery: dict) -> dict:
    """Create a git branch, add module, and submit PR."""
    
    branch_name = f"add-{module_name}-scanner"
    module_file = MODULES_DIR / f"{module_name}_scanner.py"
    
    try:
        # Ensure we're on master and up to date
        subprocess.run(["git", "checkout", "master"], cwd=PROJECT_DIR, capture_output=True)
        subprocess.run(["git", "pull", "origin", "master"], cwd=PROJECT_DIR, capture_output=True)
        
        # Create new branch
        subprocess.run(["git", "checkout", "-b", branch_name], cwd=PROJECT_DIR, capture_output=True)
        
        # Write module file
        module_file.write_text(module_code)
        
        # Add and commit
        subprocess.run(["git", "add", str(module_file)], cwd=PROJECT_DIR, capture_output=True)
        
        commit_msg = f"""Add {module_name} scanner module

Auto-generated by PR Agent based on security discovery:
- Title: {discovery.get('title', 'N/A')[:100]}
- Category: {discovery.get('category', 'N/A')}
- Source: {discovery.get('source', 'N/A')}

This module requires implementation of the actual detection logic.
"""
        subprocess.run(["git", "commit", "-m", commit_msg], cwd=PROJECT_DIR, capture_output=True)
        
        # Push branch
        result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            cwd=PROJECT_DIR,
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            raise Exception(f"Git push failed: {result.stderr}")
        
        # Create PR using gh CLI
        pr_title = f"Add {module_name} scanner module"
        pr_body = f"""## New Scanner Module

Auto-generated by PR Agent based on security discovery.

### Discovery Details
- **Title**: {discovery.get('title', 'N/A')}
- **Category**: {discovery.get('category', 'N/A')}
- **Source**: {discovery.get('source', 'N/A')}
- **Description**: {discovery.get('description', 'N/A')[:200]}

### Module
- File: `modules/{module_name}_scanner.py`
- Class: `{module_name.title().replace('_', '')}Scanner`

### TODO
- [ ] Implement actual detection logic
- [ ] Add unit tests
- [ ] Update module registry in `web/app.py`

---
*This PR was auto-generated by the PR Agent.*
"""
        
        pr_result = subprocess.run(
            ["gh", "pr", "create", "--title", pr_title, "--body", pr_body],
            cwd=PROJECT_DIR,
            capture_output=True,
            text=True
        )
        
        if pr_result.returncode != 0:
            raise Exception(f"PR creation failed: {pr_result.stderr}")
        
        # Parse PR URL/number from output
        pr_url = pr_result.stdout.strip()
        pr_number = int(pr_url.split("/")[-1]) if "/" in pr_url else 0
        
        # Switch back to master
        subprocess.run(["git", "checkout", "master"], cwd=PROJECT_DIR, capture_output=True)
        
        return {
            "success": True,
            "pr_number": pr_number,
            "pr_url": pr_url,
            "branch": branch_name,
            "module_file": str(module_file)
        }
        
    except Exception as e:
        # Clean up on failure
        subprocess.run(["git", "checkout", "master"], cwd=PROJECT_DIR, capture_output=True)
        subprocess.run(["git", "branch", "-D", branch_name], cwd=PROJECT_DIR, capture_output=True)
        
        return {
            "success": False,
            "error": str(e)
        }


def process_discovery(discovery_id: int) -> dict:
    """Process a discovery and generate a PR."""
    
    print(f"[{datetime.now(timezone.utc).isoformat()}] Processing discovery #{discovery_id}...")
    
    agent_manager.update_agent_status("pr_agent", "active")
    agent_manager.add_activity("pr_agent", f"Processing discovery #{discovery_id}")
    
    # Get discovery
    discoveries = agent_manager.get_discoveries(limit=100)
    discovery = next((d for d in discoveries if d.get("id") == discovery_id), None)
    
    if not discovery:
        agent_manager.update_agent_status("pr_agent", "error", f"Discovery #{discovery_id} not found")
        return {"success": False, "error": "Discovery not found"}
    
    # Generate module name from title
    title = discovery.get("title", "unknown")
    # Create a simple module name
    words = title.lower().split()[:3]
    module_name = "_".join(w for w in words if w.isalnum())[:30]
    
    if not module_name:
        module_name = f"custom_{discovery_id}"
    
    agent_manager.add_activity("pr_agent", f"Generating module: {module_name}")
    
    # Generate code
    module_code = generate_module_code(
        name=module_name,
        description=discovery.get("description", "")[:100],
        check_type=discovery.get("category", "vulnerability")
    )
    
    # Create branch and PR
    agent_manager.add_activity("pr_agent", f"Creating PR for {module_name}...")
    result = create_branch_and_pr(module_name, module_code, discovery)
    
    if result["success"]:
        agent_manager.increment_stat("pr_agent", "prs_opened")
        agent_manager.add_activity("pr_agent", f"Opened PR #{result['pr_number']}: {module_name}")
        agent_manager.update_discovery_status(discovery_id, "implemented")
        agent_manager.update_agent_status("pr_agent", "idle", f"PR #{result['pr_number']} created")
        print(f"✅ PR created: {result['pr_url']}")
    else:
        agent_manager.add_activity("pr_agent", f"Failed: {result.get('error', 'Unknown error')}")
        agent_manager.update_agent_status("pr_agent", "error", result.get("error", "Unknown error"))
        print(f"❌ Failed: {result.get('error')}")
    
    return result


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: pr_agent_runner.py <discovery_id>")
        print("       pr_agent_runner.py --list  (list pending discoveries)")
        sys.exit(1)
    
    if sys.argv[1] == "--list":
        discoveries = agent_manager.get_discoveries(limit=20, status="reviewing")
        print("Discoveries ready for implementation:")
        for d in discoveries:
            print(f"  #{d['id']}: [{d['category']}] {d['title'][:60]}...")
    else:
        discovery_id = int(sys.argv[1])
        result = process_discovery(discovery_id)
        sys.exit(0 if result.get("success") else 1)
